server:
  port: 80

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/


# Feign 客户端默认只等待 1 秒钟， 但是服务端处理过程超过 1 秒钟。导致Feign客户端不想等待，直接返回报错
# 如果要避免这种情况，有时候我们需要设置Fegin客户端的超时控制
ribbon:
  ReadTimeout: 5000 #指的是建立连接所用的时间，适用于网络状况正常的情况下,两端连接所用的时间
  ConnectTimeout: 5000 #指的是建立连接后从服务器读取到可用资源所用的时间

logging:
  level:
  # feign日志以什么级别监控哪个接口
    com.xiaolanhe.services.PaymentFeignService: debug